/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIsta;

import Controlador.ConsultasSQLiteDB;
import Modelo.Examenes;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Alma Cuevas
 */
public class Materias extends javax.swing.JPanel {

    ConsultasSQLiteDB conSQL = new ConsultasSQLiteDB();
    public DefaultListModel modeloListaMateria;
    public String MateriaActual;
//    PanelAlumno panelalumno = new PanelAlumno();

    /**
     * Creates new form NewJPanel
     */
    public Materias() {

        initComponents();
        modeloListaMateria = new DefaultListModel();
        ListaExamenesPlasmada.setModel(modeloListaMateria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelMateria = new javax.swing.JLabel();
        LabelAlumno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaExamenesPlasmada = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        LabelMateria.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        LabelMateria.setText("Nombre Materia");
        add(LabelMateria);
        LabelMateria.setBounds(47, 6, 317, 62);

        LabelAlumno.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        LabelAlumno.setText("Lista de Examenes:");
        add(LabelAlumno);
        LabelAlumno.setBounds(280, 80, 223, 37);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        add(jLabel6);
        jLabel6.setBounds(980, 10, 27, 30);

        ListaExamenesPlasmada.setForeground(new java.awt.Color(102, 102, 102));
        ListaExamenesPlasmada.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaExamenesPlasmada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListaExamenesPlasmadaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(ListaExamenesPlasmada);

        add(jScrollPane1);
        jScrollPane1.setBounds(180, 160, 480, 240);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void ListaExamenesPlasmadaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaExamenesPlasmadaMousePressed
        System.out.println("Me presionaste");
    }//GEN-LAST:event_ListaExamenesPlasmadaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LabelAlumno;
    public javax.swing.JLabel LabelMateria;
    public javax.swing.JList<String> ListaExamenesPlasmada;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void RellenarListaExamenes(ArrayList<Examenes> MiListaExamenes) {
        
        
        LabelMateria.setText(MateriaActual);
        modeloListaMateria.removeAllElements();
        for (Examenes mle : MiListaExamenes) {
            modeloListaMateria.addElement(mle.getNombreE());
        }
    }

}
