/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIsta;

import Conexiones.ConexionSQLite;
import Modelo.Examenes;
import Modelo.MateriasAlumno;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Alma Cuevas
 */
public class PanelAlumno extends javax.swing.JPanel {

    Materias materias = new Materias();
    public DefaultListModel modeloLista;
    //Principal principal = new Principal();
    Controlador.ConsultasSQLiteDB cSQLite = new Controlador.ConsultasSQLiteDB();
    ArrayList<MateriasAlumno> ListaDELasMaterias = new ArrayList<>();

    public PanelAlumno() {
        initComponents();
        modeloLista = new DefaultListModel();
        ListaMaterias.setModel(modeloLista);
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaMaterias = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(290, 900));

        Barra.setBackground(new java.awt.Color(255, 102, 102));
        Barra.setForeground(new java.awt.Color(0, 0, 204));
        Barra.setPreferredSize(new java.awt.Dimension(357, 1000));

        logo.setBackground(new java.awt.Color(255, 125, 125));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoP.png"))); // NOI18N
        logo.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Materias");

        ListaMaterias.setBackground(new java.awt.Color(255, 102, 102));
        ListaMaterias.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        ListaMaterias.setForeground(new java.awt.Color(51, 51, 51));
        ListaMaterias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaMaterias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListaMateriasMousePressed(evt);
            }
        });
        ListaMaterias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaMateriasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaMaterias);

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Agregar clase");

        salir.setText("cerrar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BarraLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2))
                    .addGroup(BarraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo))
                    .addGroup(BarraLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BarraLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ListaMateriasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaMateriasValueChanged
//
    }//GEN-LAST:event_ListaMateriasValueChanged

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        
        materias.setVisible(false);
        removeAll();
    }//GEN-LAST:event_salirActionPerformed

    private void ListaMateriasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMateriasMousePressed

        materias.setVisible(true);
        materias.setLocation(304, 0);
        materias.setSize(1100, 800);
        try { //Arreglar en unas horas pls
            // TODO add your handling code here:

            validaridMateria();
        } catch (SQLException ex) {
            Logger.getLogger("ALGO FALLO EN LA PARTE DE VALIDAR MATERIA" + ex);
        }
    }//GEN-LAST:event_ListaMateriasMousePressed
    public void inicio() {
        materias.setVisible(false);
        this.add(materias);
        this.revalidate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Barra;
    public javax.swing.JList<String> ListaMaterias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    public javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

    public void RellenarLista(ArrayList<MateriasAlumno> ListaMaterias) {

        for (MateriasAlumno ListaMateria : ListaMaterias) {
            modeloLista.addElement(ListaMateria.getMateria());
        }

    }

    public void removeAll() {
        modeloLista.removeAllElements();
    }

    public void validaridMateria() throws SQLException {

        String idMateria = "";
        for (MateriasAlumno object : ListaDELasMaterias) {

            if (object.getMateria().equals(ListaMaterias.getSelectedValue())) {

                idMateria = object.getId();
                ArrayList<Examenes> MiListaExamenes = cSQLite.obtenerExamenes(idMateria);
                materias.MateriaActual = GetMateriaSeleccionada();
                materias.RellenarListaExamenes(MiListaExamenes);
                break;
            }
        }

    }

    public String GetMateriaSeleccionada() {
        return ListaMaterias.getSelectedValue();
    }

}
