/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIsta;

import VIsta.Materias;
import VIsta.Login;
import VIsta.BarraInmovil;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.netbeans.lib.awtextra.AbsoluteConstraints;



/**
 *
 * @author Alma Cuevas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Login lo=new Login();
    BarraInmovil barraInmovil= new BarraInmovil();
    Materias materias= new Materias();
    public Principal() {
        inicio();
        elementodDeInicio();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoP.png"))); // NOI18N
        log.setText("jLabel1");

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoPrin.jpg"))); // NOI18N
        fondo.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(log))
            .addComponent(fondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public void elementodDeInicio(){
        //paneles necesarios se cargan al inicio 
        this.getContentPane().add(barraInmovil); // barra lateral
          //sus eventos 
           //evento del boton salir de barra lateal
             barraInmovil.salir.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                 fondo.setVisible(true);
                 log.setVisible(true);
                 lo.setVisible(true); 
                 barraInmovil.setVisible(false);
                 materias.setVisible(false);
                 }    });
                
             barraInmovil.ListaMaterias.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                materias.setVisible(true);
                materias.setLocation(304, 0);
                materias.setSize(1100, 800);
            }});
        
        this.getContentPane().add(lo); ///panel login
           //evento de entrat de login
             lo.OK.addActionListener(new ActionListener(){
                @Override
                 public void actionPerformed(ActionEvent e) {
                  validar();} });
        
        this.getContentPane().add(materias);
            
    }
    public void inicio(){
        this.getContentPane().setBackground(new java.awt.Color( 204,204,204));
        this.setExtendedState(Principal.MAXIMIZED_BOTH);
        lo.setSize(309, 554 );
        lo.setLocation(980, 160);
        lo.setVisible(true);
    }
    public void validar(){
        //elementos de inicio 
        fondo.setVisible(false);
        log.setVisible(false);
        lo.setVisible(false);
        //barra Lateral 
        barraInmovil.setSize(304,800);
        barraInmovil.setVisible(true);      
               
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel log;
    // End of variables declaration//GEN-END:variables
}
